name: Run Discord Bot

on:
  schedule:
    - cron: '45 11 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 210
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Discord Bot
        run: python "Roles bot/main.py"
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MAGMA_CHANNEL_ID: ${{ secrets.MAGMA_CHAT }}
          AQUA_CHANNEL_ID: ${{ secrets.AQUA_CHAT }}
          MAGMA_ROLE_ID: ${{ secrets.TEAM_MAGMA }}
          AQUA_ROLE_ID: ${{ secrets.TEAM_AQUA }}
