name: Run Roles Bot

on:
  schedule:
    - cron: '30 11 * * 5' 
    - cron: '30 11 * * 6' 
    - cron: '30 11 * * 0'  
  workflow_dispatch:

concurrency:
  group: roles-bot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Roles Bot
        run: python "Roles bot/main.py"
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
